### ISSUE TITLE
Add mapped_files support

### ISSUE THREAD

**Issue by stockleyy** [jslay88/qbt_migrate#4]
Win -> Linux working for a large majority of files but...

A significant minority of files are changed incorrectly.. 
Reason is as follows.

Some torrents have the list of files encoded differently. I think the bencoded data points to a list of files. Changing the path value is not enough for these torrents.

The script works but only updating the main path. 
Open the torrent and you'll find that the backslashes in the lower folders remain unchanged.

For example:
main path = /mnt/disk

Looking in client:
/mnt/disk/George Carlin\Audio\(1963) Burns and Carlin at the Playboy Club\01 - Mothers Club.mp3
/mnt/disk/George Carlin\Audio\(1963) Burns and Carlin at the Playboy Club\02 - Killer Carlin.mp3

**Comment by jslay88** [comment]
Yes, this has been fixed with the recent changes.

**Comment by jslay88** [comment]
```
Existing Path: P:\Media
New Path: /media
Target OS (Windows, Linux, Mac, Blank for same as existing): Linux

...

INFO:qbt_migrate.classes.QBTBatchMove:Updating File C:\Users\jslay\AppData\Local\qBittorrent\BT_backup\fed44a6de5570b345c56625950de4e198028b79d.f
astresume...
DEBUG:qbt_migrate.methods:Convert to Unix Slashes
DEBUG:qbt_migrate.classes.FastResume:Setting save_path... Old: P:\Media\TV Shows\Brooklyn Nine-Nine\Season 5\, New: /media/TV Shows/Brooklyn Nine
-Nine/Season 5/, Target OS: Linux
DEBUG:qbt_migrate.methods:Convert to Unix Slashes
DEBUG:qbt_migrate.classes.FastResume:Setting qBt-savePath... Old: P:\Media\TV Shows\Brooklyn Nine-Nine\Season 5\, New: /media/TV Shows/Brooklyn N
ine-Nine/Season 5/, Target OS: Linux
INFO:qbt_migrate.classes.FastResume:Saving File C:\Users\jslay\AppData\Local\qBittorrent\BT_backup\fed44a6de5570b345c56625950de4e198028b79d.fastr
esume...
INFO:qbt_migrate.classes.QBTBatchMove:File (C:\Users\jslay\AppData\Local\qBittorrent\BT_backup\fed44a6de5570b345c56625950de4e198028b79d.fastresum
e) Updated!
```

**Comment by jslay88** [comment]
```
Existing Path: P:\Media
New Path: /media
Target OS (Windows, Linux, Mac, Blank for same as existing): Linux

...

INFO:qbt_migrate.classes.QBTBatchMove:Updating File C:\Users\jslay\AppData\Local\qBittorrent\BT_backup\fed44a6de5570b345c56625950de4e198028b79d.f
astresume...
DEBUG:qbt_migrate.methods:Convert to Unix Slashes
DEBUG:qbt_migrate.classes.FastResume:Setting save_path... Old: P:\Media\TV Shows\A TV Show\Season 5\, New: /media/TV Shows/A TV Show/Season 5/, Target OS: Linux
DEBUG:qbt_migrate.methods:Convert to Unix Slashes
DEBUG:qbt_migrate.classes.FastResume:Setting qBt-savePath... Old: P:\Media\TV Shows\A TV Show\Season 5\, New: /media/TV Shows/A TV Show/Season 5/, Target OS: Linux
INFO:qbt_migrate.classes.FastResume:Saving File C:\Users\jslay\AppData\Local\qBittorrent\BT_backup\fed44a6de5570b345c56625950de4e198028b79d.fastr
esume...
INFO:qbt_migrate.classes.QBTBatchMove:File (C:\Users\jslay\AppData\Local\qBittorrent\BT_backup\fed44a6de5570b345c56625950de4e198028b79d.fastresum
e) Updated!
```

**Comment by stockleyy** [comment]
Still having issues jslay88...
25% of files don't have their subpaths changed

**Comment by jslay88** [comment]
Then you are going to have to provide the fastresume files, because all of the ones I have between windows and linux are now testing out perfectly (1200 torrents).

You are using the newest updated cli.py, correct?

**Comment by stockleyy** [comment]
yes.
I think your script doesn't change paths which reside in the bencoded "mapped_files" field, correct?
These often contain references to paths too.

**Comment by jslay88** [comment]
Ahh yes, I don't have that field in my files. Weird. Will add support in a few hours once I wrap up work.

Thanks for your patience.

**Comment by jslay88** [comment]
Grab the new commits on master, install the requirements with pip.

```
pip install -r requirements.txt
```

**Comment by jslay88** [comment]
Here is is patched with the new version of the script.
[example.fastresume.zip](https://github.com/jslay88/qbt_migrate/files/4280195/example.fastresume.zip)

**Comment by stockleyy** [comment]
Works like a charm. thanks!
